version: "3.9"

services:
  frontend:
    build: ./ecommerce/services/frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./ecommerce/services/api-gateway
    container_name: api-gateway
    ports:
      - "3002:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  user-service:
    build: ./ecommerce/services/user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  product-service:
    build: ./ecommerce/services/product-service
    container_name: product-service
    ports:
      - "3005:3000"

  order-service:
    build: ./ecommerce/services/order-service
    container_name: order-service
    ports:
      - "3003:3000"

  payment-service:
    build: ./ecommerce/services/payment-service
    container_name: payment-service
    ports:
      - "3004:3000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
